// <auto-generated />
namespace WebExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PostDataAnnotations2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostDataAnnotations2));
        
        string IMigrationMetadata.Id
        {
            get { return "202010171434109_PostDataAnnotations2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
